# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './qt_designer/ui_markme.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWidget(object):
    def setupUi(self, MainWidget):
        MainWidget.setObjectName("MainWidget")
        MainWidget.resize(827, 939)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWidget.sizePolicy().hasHeightForWidth())
        MainWidget.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../ui/mark_me.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWidget.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(MainWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 4, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(-1, -1, 0, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_3 = QtWidgets.QLabel(MainWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_8.addWidget(self.label_3)
        self.labelOriginal = CanvasView(MainWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelOriginal.sizePolicy().hasHeightForWidth())
        self.labelOriginal.setSizePolicy(sizePolicy)
        self.labelOriginal.setMinimumSize(QtCore.QSize(400, 400))
        self.labelOriginal.setMaximumSize(QtCore.QSize(400, 400))
        font = QtGui.QFont()
        font.setFamily("MS UI Gothic")
        font.setBold(False)
        font.setWeight(50)
        self.labelOriginal.setFont(font)
        self.labelOriginal.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.labelOriginal.setObjectName("labelOriginal")
        self.verticalLayout_8.addWidget(self.labelOriginal)
        self.line_5 = QtWidgets.QFrame(MainWidget)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout_8.addWidget(self.line_5)
        self.label_4 = QtWidgets.QLabel(MainWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS UI Gothic")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_8.addWidget(self.label_4)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.buttonClearMark = QtWidgets.QPushButton(MainWidget)
        self.buttonClearMark.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.buttonClearMark.setFont(font)
        self.buttonClearMark.setObjectName("buttonClearMark")
        self.horizontalLayout_7.addWidget(self.buttonClearMark)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.buttonUndoMark = QtWidgets.QPushButton(MainWidget)
        self.buttonUndoMark.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.buttonUndoMark.setFont(font)
        self.buttonUndoMark.setObjectName("buttonUndoMark")
        self.horizontalLayout_7.addWidget(self.buttonUndoMark)
        self.buttonRedoMark = QtWidgets.QPushButton(MainWidget)
        self.buttonRedoMark.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.buttonRedoMark.setFont(font)
        self.buttonRedoMark.setObjectName("buttonRedoMark")
        self.horizontalLayout_7.addWidget(self.buttonRedoMark)
        self.verticalLayout_8.addLayout(self.horizontalLayout_7)
        self.labelImage = CanvasView(MainWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelImage.sizePolicy().hasHeightForWidth())
        self.labelImage.setSizePolicy(sizePolicy)
        self.labelImage.setMinimumSize(QtCore.QSize(400, 400))
        self.labelImage.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.labelImage.setObjectName("labelImage")
        self.verticalLayout_8.addWidget(self.labelImage)
        self.horizontalLayout_10.addLayout(self.verticalLayout_8)
        self.line_2 = QtWidgets.QFrame(MainWidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_10.addWidget(self.line_2)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_5 = QtWidgets.QLabel(MainWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_4.addWidget(self.label_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.labelHistogram = QtWidgets.QLabel(MainWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelHistogram.sizePolicy().hasHeightForWidth())
        self.labelHistogram.setSizePolicy(sizePolicy)
        self.labelHistogram.setMinimumSize(QtCore.QSize(300, 150))
        self.labelHistogram.setMaximumSize(QtCore.QSize(300, 150))
        self.labelHistogram.setObjectName("labelHistogram")
        self.horizontalLayout_4.addWidget(self.labelHistogram)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_6 = QtWidgets.QLabel(MainWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_10.addWidget(self.label_6)
        self.horizontalLayout_4.addLayout(self.verticalLayout_10)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(MainWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(40, 30))
        self.label_2.setMaximumSize(QtCore.QSize(20, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.sliderMinHistogram = QtWidgets.QSlider(MainWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sliderMinHistogram.sizePolicy().hasHeightForWidth())
        self.sliderMinHistogram.setSizePolicy(sizePolicy)
        self.sliderMinHistogram.setMinimumSize(QtCore.QSize(300, 0))
        self.sliderMinHistogram.setOrientation(QtCore.Qt.Horizontal)
        self.sliderMinHistogram.setObjectName("sliderMinHistogram")
        self.horizontalLayout_2.addWidget(self.sliderMinHistogram)
        self.spinMinHistogram = QtWidgets.QSpinBox(MainWidget)
        self.spinMinHistogram.setMinimumSize(QtCore.QSize(50, 0))
        self.spinMinHistogram.setObjectName("spinMinHistogram")
        self.horizontalLayout_2.addWidget(self.spinMinHistogram)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(MainWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(40, 30))
        self.label.setMaximumSize(QtCore.QSize(20, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.sliderMaxHistogram = QtWidgets.QSlider(MainWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sliderMaxHistogram.sizePolicy().hasHeightForWidth())
        self.sliderMaxHistogram.setSizePolicy(sizePolicy)
        self.sliderMaxHistogram.setMinimumSize(QtCore.QSize(300, 0))
        self.sliderMaxHistogram.setOrientation(QtCore.Qt.Horizontal)
        self.sliderMaxHistogram.setObjectName("sliderMaxHistogram")
        self.horizontalLayout.addWidget(self.sliderMaxHistogram)
        self.spinMaxHistogram = QtWidgets.QSpinBox(MainWidget)
        self.spinMaxHistogram.setMinimumSize(QtCore.QSize(50, 0))
        self.spinMaxHistogram.setObjectName("spinMaxHistogram")
        self.horizontalLayout.addWidget(self.spinMaxHistogram)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.line_4 = QtWidgets.QFrame(MainWidget)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_4.addWidget(self.line_4)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem2)
        self.label_7 = QtWidgets.QLabel(MainWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_4.addWidget(self.label_7)
        self.groupBox = QtWidgets.QGroupBox(MainWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.groupBox)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(9, 19, 381, 71))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_6.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_8 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_6.addWidget(self.label_8)
        self.radioButton1 = QtWidgets.QRadioButton(self.horizontalLayoutWidget_4)
        self.radioButton1.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.radioButton1.setFont(font)
        self.radioButton1.setIconSize(QtCore.QSize(30, 30))
        self.radioButton1.setObjectName("radioButton1")
        self.verticalLayout_6.addWidget(self.radioButton1)
        self.horizontalLayout_6.addLayout(self.verticalLayout_6)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_9 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_7.addWidget(self.label_9)
        self.radioButton2 = QtWidgets.QRadioButton(self.horizontalLayoutWidget_4)
        self.radioButton2.setObjectName("radioButton2")
        self.verticalLayout_7.addWidget(self.radioButton2)
        self.horizontalLayout_6.addLayout(self.verticalLayout_7)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_10 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_11.addWidget(self.label_10)
        self.radioButton3 = QtWidgets.QRadioButton(self.horizontalLayoutWidget_4)
        self.radioButton3.setObjectName("radioButton3")
        self.verticalLayout_11.addWidget(self.radioButton3)
        self.horizontalLayout_6.addLayout(self.verticalLayout_11)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_11 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_13.addWidget(self.label_11)
        self.radioButton4 = QtWidgets.QRadioButton(self.horizontalLayoutWidget_4)
        self.radioButton4.setObjectName("radioButton4")
        self.verticalLayout_13.addWidget(self.radioButton4)
        self.horizontalLayout_6.addLayout(self.verticalLayout_13)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_12 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_15.addWidget(self.label_12)
        self.radioButton5 = QtWidgets.QRadioButton(self.horizontalLayoutWidget_4)
        self.radioButton5.setObjectName("radioButton5")
        self.verticalLayout_15.addWidget(self.radioButton5)
        self.horizontalLayout_6.addLayout(self.verticalLayout_15)
        self.verticalLayout_4.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(MainWidget)
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 350))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayoutWidget_9 = QtWidgets.QWidget(self.groupBox_2)
        self.verticalLayoutWidget_9.setGeometry(QtCore.QRect(10, 20, 381, 311))
        self.verticalLayoutWidget_9.setObjectName("verticalLayoutWidget_9")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_9)
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem3)
        self.buttonClearComment = QtWidgets.QPushButton(self.verticalLayoutWidget_9)
        self.buttonClearComment.setMinimumSize(QtCore.QSize(0, 25))
        self.buttonClearComment.setObjectName("buttonClearComment")
        self.horizontalLayout_9.addWidget(self.buttonClearComment)
        self.verticalLayout_16.addLayout(self.horizontalLayout_9)
        self.textEditComment = QtWidgets.QTextEdit(self.verticalLayoutWidget_9)
        self.textEditComment.setObjectName("textEditComment")
        self.verticalLayout_16.addWidget(self.textEditComment)
        self.verticalLayout_4.addWidget(self.groupBox_2)
        self.horizontalLayout_10.addLayout(self.verticalLayout_4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_10)
        self.line = QtWidgets.QFrame(MainWidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_3.addWidget(self.line)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.progressBarIndex = QtWidgets.QProgressBar(MainWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.progressBarIndex.setFont(font)
        self.progressBarIndex.setProperty("value", 24)
        self.progressBarIndex.setObjectName("progressBarIndex")
        self.horizontalLayout_8.addWidget(self.progressBarIndex)
        self.buttonPrevIndex = QtWidgets.QPushButton(MainWidget)
        self.buttonPrevIndex.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.buttonPrevIndex.setFont(font)
        self.buttonPrevIndex.setObjectName("buttonPrevIndex")
        self.horizontalLayout_8.addWidget(self.buttonPrevIndex)
        self.buttonNextIndex = QtWidgets.QPushButton(MainWidget)
        self.buttonNextIndex.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.buttonNextIndex.setFont(font)
        self.buttonNextIndex.setObjectName("buttonNextIndex")
        self.horizontalLayout_8.addWidget(self.buttonNextIndex)
        self.buttonCompleteIndex = QtWidgets.QPushButton(MainWidget)
        self.buttonCompleteIndex.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.buttonCompleteIndex.setFont(font)
        self.buttonCompleteIndex.setObjectName("buttonCompleteIndex")
        self.horizontalLayout_8.addWidget(self.buttonCompleteIndex)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.verticalLayout_9.addLayout(self.horizontalLayout_3)
        self.verticalLayout.addLayout(self.verticalLayout_9)

        self.retranslateUi(MainWidget)
        QtCore.QMetaObject.connectSlotsByName(MainWidget)

    def retranslateUi(self, MainWidget):
        _translate = QtCore.QCoreApplication.translate
        MainWidget.setWindowTitle(_translate("MainWidget", "Mark me (Kyoto Institute of Technology)"))
        self.label_3.setText(_translate("MainWidget", "Original Image"))
        self.labelOriginal.setText(_translate("MainWidget", "labelOriginal"))
        self.label_4.setText(_translate("MainWidget", "Marked image"))
        self.buttonClearMark.setText(_translate("MainWidget", "Clear"))
        self.buttonUndoMark.setText(_translate("MainWidget", "Undo"))
        self.buttonRedoMark.setText(_translate("MainWidget", "Redo"))
        self.labelImage.setText(_translate("MainWidget", "labelImage"))
        self.label_5.setText(_translate("MainWidget", "Histogram"))
        self.labelHistogram.setText(_translate("MainWidget", "TextLabel"))
        self.label_6.setText(_translate("MainWidget", "HU value"))
        self.label_2.setStatusTip(_translate("MainWidget", "0"))
        self.label_2.setText(_translate("MainWidget", "min"))
        self.label.setText(_translate("MainWidget", "max"))
        self.label_7.setText(_translate("MainWidget", "Label"))
        self.groupBox.setTitle(_translate("MainWidget", "Malignancy"))
        self.label_8.setText(_translate("MainWidget", "Benign"))
        self.radioButton1.setText(_translate("MainWidget", "1"))
        self.label_9.setText(_translate("MainWidget", "-"))
        self.radioButton2.setText(_translate("MainWidget", "2"))
        self.label_10.setText(_translate("MainWidget", "-"))
        self.radioButton3.setText(_translate("MainWidget", "3"))
        self.label_11.setText(_translate("MainWidget", "-"))
        self.radioButton4.setText(_translate("MainWidget", "4"))
        self.label_12.setText(_translate("MainWidget", "Malignant"))
        self.radioButton5.setText(_translate("MainWidget", "5"))
        self.groupBox_2.setTitle(_translate("MainWidget", "Comments"))
        self.buttonClearComment.setText(_translate("MainWidget", "Clear"))
        self.progressBarIndex.setFormat(_translate("MainWidget", "%v / %m"))
        self.buttonPrevIndex.setText(_translate("MainWidget", "Prev"))
        self.buttonNextIndex.setText(_translate("MainWidget", "Next"))
        self.buttonCompleteIndex.setText(_translate("MainWidget", "Complete"))

from view.canvas_view import CanvasView
